name: publish
on: [push]
jobs:
  build_and_publish:
     runs-on: ubuntu-latest
     steps:
   - uses: actions/checkout@v2
#- name: Login to GitHub Container Registry
   - name: Build the hello-docker Docker image
#uses: docker/login-action@v1
#with:
#registry: ghcr.io
#username: ${{ github.actor }}
#password: ${{ secrets.GH_TOKEN }}

#- name: Build the hello-docker Docker image
      run: |
        docker login --username mlsysadmin --password ${{ secrets.GH_TOKEN }} ghcr.io
        docker build . --tag ghcr.io/mlsysadmin/hello-world-ghcr:latest
        docker run ghcr.io/mlsysadmin/hello-world-ghcr:latest
